FROM nginx:alpine

# Limpia la carpeta por defecto de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia tu frontend y el logo (deben estar dentro de /app)
COPY index.html /usr/share/nginx/html/index.html
COPY uce-logo.png /usr/share/nginx/html/uce-logo.png

# Puerto de Nginx
EXPOSE 80

# Ejecuta Nginx
CMD ["nginx", "-g", "daemon off;"]

